name: CICD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t solutions1313temp/latest-book-backend .
      - name: Publish image to docker hub
        run: docker push solutions1313temp/latest-book-backend:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull solutions1313temp/latest-book-backend:latest
      - name: Delete old container
        run: docker rm -f latest-book-backend-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name latest-book-backend-container solutions1313temp/latest-book-backend
